### ISSUE TITLE
Issue building grok on CentOS 7

### ISSUE THREAD

**Issue by jamesberes** [GrokImageCompression/grok#131]
I'm trying to build everything in a docker container and I've been stumped for a while now... 

I'm building from the docker image here:
https://hub.docker.com/r/fabric8/java-centos-openjdk8-jdk/ which seems fairly popular. 

Base-Image: CentOS 7
Java: OpenJDK 8 1.8.0 (Java Development Kit (JDK))
gcc --version: 4.8.5

In my Dockerfile I have:
```
FROM fabric8/java-centos-openjdk8-jdk

USER root

RUN yum -y update && \
    yum repolist && \
    yum -y install gcc gcc-c++ wget ca-certificates \
      ImageMagick ghostscript \
      curl vim zip make git tar epel-release gmp-devel mpfr-devel libmpc-devel

#Build cmake
WORKDIR /tmp/cmake
RUN wget http://www.cmake.org/files/v3.12/cmake-3.12.2.tar.gz && tar xf cmake-3.12.2.tar.gz && cd cmake-3.12.2 && ./configure && make && make install

# Download and compile Grok master
WORKDIR /tmp/openjpeg
RUN git clone https://github.com/GrokImageCompression/grok.git ./
RUN cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_THIRDPARTY:BOOL=ON . && make && make install

WORKDIR /
COPY . /build
RUN /build/setup.sh

```

The following is a bit of the output I thought might be useful information: 

2019-08-14 21:20:52 (7.76 MB/s) - 'cmake-3.12.2.tar.gz' saved [8388114/8388114]
CMake 3.12.2, Copyright 2000-2018 Kitware, Inc. and Contributors
Found GNU toolchain
C compiler on this system is: gcc       
C++ compiler on this system is: g++  -std=gnu++1y     
Makefile processor on this system is: gmake
g++ has setenv
g++ has unsetenv
g++ does not have environ in stdlib.h
g++ has stl wstring
g++ has <ext/stdio_filebuf.h>
...
...
loading initial cache file /tmp/cmake/cmake-3.12.2/Bootstrap.cmk/InitialCacheFlags.cmake
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
...
...
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
...
...
-- Checking if compiler supports C11 _Thread_local
-- Checking if compiler supports C11 _Thread_local - no
-- Checking if compiler supports needed C++14 constructs
-- Checking if compiler supports needed C++14 constructs - yes
...
...
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/cmake/cmake-3.12.2

CMake has bootstrapped.  Now run gmake.
Scanning dependencies of target cmsys
[  1%] Building C object Source/kwsys/CMakeFiles/cmsys.dir/ProcessUNIX.c.o
...
...
**_//everything seems to be going fine... modules begin installing_**
-- Installing: /usr/local/share/cmake-3.12/Modules/CPackCygwin.cmake

**_//we get passed cmake install and onto grok install_**
Step 11/21 : RUN git clone https://github.com/GrokImageCompression/grok.git ./
 ---> Running in 419035ffb0ca
Cloning into '.'...
Removing intermediate container 419035ffb0ca
 ---> d9296fbcf420
Step 13/21 : RUN cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_THIRDPARTY:BOOL=ON . && make && make install
 ---> Running in e21d43733d3c
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc -- works
...
...
-- Check for working CXX compiler: /usr/bin/c++ -- works

**//Missing JPEG library**
-- Looking for setmod - not found
-- We will build LCMS2 lib from thirdparty
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR) 
-- JPEG lib not found, please install or build from source and make sure install directory is on path
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/openjpeg
Scanning dependencies of target openjp2_static
[  0%] Building CXX object src/lib/openjp2/CMakeFiles/openjp2_static.dir/BitIO.cpp.o
...
...

_**//First interruption**_
```
[ 23%] Building CXX object src/lib/openjp2/CMakeFiles/openjp2.dir/j2k.cpp.o
/tmp/openjpeg/src/lib/openjp2/j2k.cpp: In function 'bool grk::j2k_update_rates(grk::j2k_t*, grk::GrokStream*, grk::event_mgr_t*)':
/tmp/openjpeg/src/lib/openjp2/j2k.cpp:4297:59: warning: conversion to 'double' from 'long unsigned int' may alter its value [-Wconversion]
                     *l_rates =  ((((double)l_size_pixel * numTilePixels))
                                                           ^
/tmp/openjpeg/src/lib/openjp2/j2k.cpp:4316:39: warning: conversion to 'double' from 'long unsigned int' may alter its value [-Wconversion]
    auto sot_adjust = (numTilePixels * header_size) / ((uint64_t)width*height);
                                       ^
/tmp/openjpeg/src/lib/openjp2/j2k.cpp:4316:70: warning: conversion to 'double' from 'uint64_t {aka long unsigned int}' may alter its value [-Wconversion]
    auto sot_adjust = (numTilePixels * header_size) / ((uint64_t)width*height);
                                                                      ^
/tmp/openjpeg/src/lib/openjp2/j2k.cpp: In function 'void grk::j2k_dump_MH_index(grk::j2k_t*, FILE*)':
/tmp/openjpeg/src/lib/openjp2/j2k.cpp:8868:38: warning: format '%lld' expects argument of type 'long long int', but argument 4 has type 'int64_t {aka long int}' [-Wformat=]
     cstr_index->marker[it_marker].len);
                                      ^
```
... continuing
_**Second interruption**_
```
[ 30%] Building CXX object src/lib/openjp2/CMakeFiles/openjp2.dir/t1_decode.cpp.o
In file included from /tmp/openjpeg/src/lib/openjp2/t1_decode.cpp:62:0:
/tmp/openjpeg/src/lib/openjp2/t1_luts.h:73:16: warning: 'lut_nmsedec_sig' defined but not used [-Wunused-variable]
 static int16_t lut_nmsedec_sig[1 << T1_NMSEDEC_BITS] = {
                ^
/tmp/openjpeg/src/lib/openjp2/t1_luts.h:92:16: warning: 'lut_nmsedec_sig0' defined but not used [-Wunused-variable]
 static int16_t lut_nmsedec_sig0[1 << T1_NMSEDEC_BITS] = {
                ^
/tmp/openjpeg/src/lib/openjp2/t1_luts.h:111:16: warning: 'lut_nmsedec_ref' defined but not used [-Wunused-variable]
 static int16_t lut_nmsedec_ref[1 << T1_NMSEDEC_BITS] = {
                ^
/tmp/openjpeg/src/lib/openjp2/t1_luts.h:130:16: warning: 'lut_nmsedec_ref0' defined but not used [-Wunused-variable]
 static int16_t lut_nmsedec_ref0[1 << T1_NMSEDEC_BITS] = {
                ^
[ 31%] Building CXX object src/lib/openjp2/CMakeFiles/openjp2.dir/t1_encode.cpp.o
In file included from /tmp/openjpeg/src/lib/openjp2/t1_encode.cpp:61:0:
/tmp/openjpeg/src/lib/openjp2/t1_luts.h:5:16: warning: 'lut_ctxno_zc' defined but not used [-Wunused-variable]
 static uint8_t lut_ctxno_zc[1024] = {
                ^
/tmp/openjpeg/src/lib/openjp2/t1_luts.h:40:16: warning: 'lut_ctxno_sc' defined but not used [-Wunused-variable]
 static uint8_t lut_ctxno_sc[256] = {
                ^
/tmp/openjpeg/src/lib/openjp2/t1_luts.h:61:16: warning: 'lut_spb' defined but not used [-Wunused-variable]
 static uint8_t lut_spb[256] = {
                ^
[ 31%] Building CXX object src/lib/openjp2/CMakeFiles/openjp2.dir/t2.cpp.o

```
Then we move forward to 86%

_**### We Fail Out...**_
```
[ 86%] Building CXX object src/bin/jp2/CMakeFiles/opj_compress.dir/__/common/common.cpp.o
/tmp/openjpeg/src/bin/common/common.cpp:80:22: error: 'chrono_literals' is not a namespace-name
 using namespace std::chrono_literals;
                      ^
/tmp/openjpeg/src/bin/common/common.cpp:80:37: error: expected namespace-name before ';' token
 using namespace std::chrono_literals;
                                     ^
/tmp/openjpeg/src/bin/common/common.cpp: In function 'int grk::batch_sleep(int)':
/tmp/openjpeg/src/bin/common/common.cpp:89:30: error: unable to find numeric literal operator 'operator"" ms'
  sleep_cv.wait_for(lk, val * 100ms, [] {return false; });
                              ^
make[2]: *** [src/bin/jp2/CMakeFiles/opj_compress.dir/__/common/common.cpp.o] Error 1
make[1]: *** [src/bin/jp2/CMakeFiles/opj_compress.dir/all] Error 2
make: *** [all] Error 2
The command '/bin/sh -c cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_THIRDPARTY:BOOL=ON . && make && make install' returned a non-zero code: 2

```

I'd formally like to apologize for puking code, but I thought it may prove helpful more than annoying. 

I've also looked through the code for previous CentOS issues with no avail but perhaps I missed something. 

Thank you in advance!

**Comment by boxerab** [comment]
Thanks for the report - just a missing header file. Fixed. now.

**Comment by jamesberes** [comment]
@boxerab 
I'm actually still getting the same issues:

```
[ 86%] Building CXX object src/bin/jp2/CMakeFiles/opj_compress.dir/__/common/common.cpp.o
/tmp/openjpeg/src/bin/common/common.cpp:81:22: error: 'chrono_literals' is not a namespace-name
 using namespace std::chrono_literals;
                      ^
/tmp/openjpeg/src/bin/common/common.cpp:81:37: error: expected namespace-name before ';' token
 using namespace std::chrono_literals;
                                     ^
/tmp/openjpeg/src/bin/common/common.cpp: In function 'int grk::batch_sleep(int)':
/tmp/openjpeg/src/bin/common/common.cpp:90:30: error: unable to find numeric literal operator 'operator"" ms'
  sleep_cv.wait_for(lk, val * 100ms, [] {return false; });
                              ^
make[2]: *** [src/bin/jp2/CMakeFiles/opj_compress.dir/__/common/common.cpp.o] Error 1
make[1]: *** [src/bin/jp2/CMakeFiles/opj_compress.dir/all] Error 2
make: *** [all] Error 2
```

though they're all one line further in common.cpp

**Comment by boxerab** [comment]
ok, try it now. Should work :)

**Comment by jamesberes** [comment]
Negative , here's how the change reflected
```
[ 86%] Building CXX object src/bin/jp2/CMakeFiles/opj_compress.dir/__/common/common.cpp.o
/tmp/openjpeg/src/bin/common/common.cpp:82:22: error: 'std::literals' has not been declared
 using namespace std::literals::chrono_literals;
                      ^
/tmp/openjpeg/src/bin/common/common.cpp:82:32: error: 'chrono_literals' is not a namespace-name
 using namespace std::literals::chrono_literals;
                                ^
/tmp/openjpeg/src/bin/common/common.cpp:82:47: error: expected namespace-name before ';' token
 using namespace std::literals::chrono_literals;
                                               ^
/tmp/openjpeg/src/bin/common/common.cpp: In function 'int grk::batch_sleep(int)':
/tmp/openjpeg/src/bin/common/common.cpp:91:30: error: unable to find numeric literal operator 'operator"" ms'
  sleep_cv.wait_for(lk, val * 100ms, [] {return false; });
                              ^
make[2]: *** [src/bin/jp2/CMakeFiles/opj_compress.dir/__/common/common.cpp.o] Error 1
make[1]: *** [src/bin/jp2/CMakeFiles/opj_compress.dir/all] Error 2
make: *** [all] Error 2
The command '/bin/sh -c cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_THIRDPARTY:BOOL=ON . && make && make install' returned a non-zero code: 2
```

**Comment by boxerab** [comment]
Which compiler and version are you using btw?

**Comment by boxerab** [comment]
Also, this method is only used by the Gpu plugin, you could just find those lines and comment them out

**Comment by boxerab** [comment]
You can try one more time - may be fixed now.

**Comment by boxerab** [comment]
> Which compiler and version are you using btw?

Oh, I see you have gcc 4.8.5

**Comment by boxerab** [comment]
That is a four year old compiler, can you upgrade to newer version ?

**Comment by boxerab** [comment]
4.8 was actually released in 2013.

**Comment by boxerab** [comment]
Best approach for you is to either upgrade compiler or comment out that line. Closing.

**Comment by jamesberes** [comment]
I have also tried 7.3, 8.2, and 9.2 which is the newest

**Comment by boxerab** [comment]
Project is known to compile with gcc 5.5 and 8.3.  I recommend just commenting out that line - you won't need it :) Good luck!
