### ISSUE TITLE
Error in minpf_plugin_manager.cpp when compiling

### ISSUE THREAD

**Issue by jweisman** [GrokImageCompression/grok#64]
Hi @boxerab. Trying to compile grok and I'm getting an error since yesterday. 

Running `cmake -DCMAKE_BUILD_TYPE=Release . && make && make install`:
````
[ 58%] Building CXX object src/lib/openjp2/CMakeFiles/openjp2.dir/minpf_plugin_manager.cpp.o
/tmp/openjpeg/src/lib/openjp2/minpf_plugin_manager.cpp:90:11: warning: missing terminating " character [enabled by default]
  return so";
           ^
/tmp/openjpeg/src/lib/openjp2/minpf_plugin_manager.cpp:90:2: error: missing terminating " character
  return so";
  ^
/tmp/openjpeg/src/lib/openjp2/minpf_plugin_manager.cpp: In function 'const char* minpf_get_dynamic_library_extension()':
/tmp/openjpeg/src/lib/openjp2/minpf_plugin_manager.cpp:90:9: error: 'so' was not declared in this scope
  return so";
         ^
/tmp/openjpeg/src/lib/openjp2/minpf_plugin_manager.cpp:93:1: error: expected ';' before '}' token
 }
 ^
make[2]: *** [src/lib/openjp2/CMakeFiles/openjp2.dir/minpf_plugin_manager.cpp.o] Error 1
make[1]: *** [src/lib/openjp2/CMakeFiles/openjp2.dir/all] Error 2
make: *** [all] Error 2
````

I see there were commits yesterday but I don't know if it's related. Any help would be appreciated. Thanks.

**Comment by boxerab** [comment]
Thanks for reporting, Josh. May I ask what OS you are running this on?

**Comment by jweisman** [comment]
Hi Aaron. Thanks for the quick response. I'm on Ubuntu 14.04.

**Comment by boxerab** [comment]
Because I am able to compile with master branch on Ubuntu 16.X

**Comment by jweisman** [comment]
I was using the 2.1.1 tag. Head doesn't compile on Ubuntu 14.04, but it does with 16.04. I will try to use that. Thanks.

**Comment by boxerab** [comment]
Thanks. Yes, 2.1.1 tag is a bit old. I suppose I should issue a new release.
