### ISSUE TITLE
unable to build on osx 10.15

### ISSUE THREAD

**Issue by sbarex** [GrokImageCompression/grok#140]
I try to compile with:
```
$ cmake .
$ make
```
The compilation fail at 22%:
```
grok/src/lib/openjp2/grok_malloc.cpp:77:8: error: use of undeclared identifier 'aligned_alloc'
        ptr = aligned_alloc(alignment, size);
              ^
1 error generated.
```

During cmake initialization it's shows this info about alloc:
```
-- Looking for include file malloc.h
-- Looking for include file malloc.h - not found
-- Looking for _aligned_malloc
-- Looking for _aligned_malloc - not found
-- Looking for aligned_alloc
-- Looking for aligned_alloc - found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for memalign
-- Looking for memalign - not found
```

**Comment by boxerab** [comment]
Thanks - unfortunately I don't have access to Catalina system. But, since `aligned_alloc` is new to 10.15, it looks like there are some header issues. Which compiler are you using - gcc or xcode ?
One workaround is to add the following line to the very beginning of  `grok_malloc.cpp` 

` #undef GROK_HAVE_ALIGNED_ALLOC`

**Comment by boxerab** [comment]
@sbarex try pulling the latest version - hopefully this fixes it for you.

**Comment by sbarex** [comment]
Thanks, the problem is both with gcc and xcode build.
After last commit now the output is:
```
src/lib/openjp2/grok_malloc.cpp:82:8: error: use of undeclared identifier 'aligned_alloc'
        ptr = aligned_alloc(alignment, size);
              ^
```

Same error but at a different line.
I see that the `GROK_HAVE_ALIGNED_ALLOC` is defined inside `grk_config_private.h` that is included by `grok_includes.h`. So your fix on last commit should not be at the beginning of the file but down the `#include "grok_includes.h"`.

**Comment by boxerab** [comment]
Thanks, fixed now :)
